import { afterEach, beforeEach, expect, test, vi } from 'vitest'
import { api, auth } from './api'
import { clearGuest, GUEST_KEY, GUEST_IMPORT_KEY, guestApi, guestCsv, guestHasRecords, guestImportSnapshot, readGuest, setGuestActive } from './guest'

const write = (path, body, method = 'POST') => guestApi(path, { method, body: JSON.stringify(body) })
const expense = (extra = {}) => ({ type: 'expense', amount: 3.125, description: 'Lunch', notes: '', date: '2026-10-05T09:00:00Z', reporting_month: null, wallet_id: 1, category_id: 2, recurring_frequency: 'none', ...extra })
beforeEach(() => { localStorage.clear(); sessionStorage.clear(); setGuestActive(false) })
afterEach(() => { vi.restoreAllMocks(); setGuestActive(false) })

test('guest records persist and never send financial requests or touch signed-in caches', async () => {
  const fetch = vi.spyOn(globalThis, 'fetch').mockRejectedValue(new Error('No network allowed'))
  setGuestActive(true)
  await api('/api/transactions', { method: 'POST', body: JSON.stringify(expense()) })
  setGuestActive(false); setGuestActive(true)
  expect((await api('/api/transactions'))[0].description).toBe('Lunch')
  expect(fetch).not.toHaveBeenCalled()
  expect(auth.token).toBe('')
  expect(guestHasRecords()).toBe(true)
})
test('two active wallets maximum including Main, enforced in the data layer', async () => {
  const payload = { name: 'Bank', type: 'bank', initial_balance: 100, color: '#75465f', card_network: 'mastercard' }
  const bank = await write('/api/wallets', payload)
  await expect(write('/api/wallets', { ...payload, name: 'Third' })).rejects.toMatchObject({ status: 403 })
  expect((await guestApi('/api/wallets'))[1]).toMatchObject({ balance: 100, color: '#75465f', card_network: 'mastercard' })
  await write(`/api/wallets/${bank.id}`, { ...payload, archived: true }, 'PUT')
  await write('/api/wallets', { ...payload, name: 'Replacement' })
  await expect(write(`/api/wallets/${bank.id}`, { ...payload, archived: false }, 'PUT')).rejects.toMatchObject({ status: 403 })
})
test('income, spending, transfers and opening balances agree across pages', async () => {
  await write('/api/wallets/1', { ...readGuest().wallets[0], initial_balance: 100 }, 'PUT')
  const bank = await write('/api/wallets', { name: 'Savings', type: 'bank', initial_balance: 0 })
  await write('/api/transactions', expense())
  await write('/api/transactions', expense({ type: 'income', category_id: 10, amount: 20, reporting_month: '2026-11' }))
  await write('/api/transactions', expense({ type: 'transfer', category_id: null, amount: 10, transfer_wallet_id: bank.id }))
  const wallets = await guestApi('/api/wallets')
  expect(wallets.map(w => w.balance)).toEqual([106.875, 10])
  const dashboard = await guestApi('/api/dashboard?month=2026-10')
  expect(dashboard.expense).toBe(3.125)
  expect(dashboard.total_balance).toBe(116.875)
  expect((await guestApi('/api/dashboard?month=2026-11')).earned_income).toBe(20)
  expect((await guestApi('/api/analytics')).categories[0].value).toBe(3.125)
})
test('month, wallet, type, search, dates and pagination filter the same records', async () => {
  await write('/api/transactions', expense())
  await write('/api/transactions', expense({ description: 'Taxi', reporting_month: '2026-11' }))
  expect(await guestApi('/api/transactions?search=lunch&month=2026-10&wallet_id=1&tx_type=expense')).toHaveLength(1)
  expect(await guestApi('/api/transactions?month=2026-11&category_id=2')).toHaveLength(1)
  expect(await guestApi('/api/transactions?offset=1&limit=1&sort=oldest')).toHaveLength(1)
  expect(await guestApi('/api/transactions?date_from=2026-10-06')).toHaveLength(0)
})
test('edit conflict detection and wallet deletion protect linked records', async () => {
  const row = await write('/api/transactions', expense())
  await expect(write(`/api/transactions/${row.id}`, { ...row, revision: '0' }, 'PUT')).rejects.toMatchObject({ status: 409 })
  const edited = await write(`/api/transactions/${row.id}`, { ...row, amount: 2 }, 'PUT')
  expect(edited.amount).toBe(2)
  await expect(guestApi('/api/wallets/1', { method: 'DELETE' })).rejects.toMatchObject({ status: 409 })
  await guestApi('/api/wallets/1?delete_transactions=true', { method: 'DELETE' })
  expect(readGuest().transactions).toHaveLength(0)
})
test('budgets use reporting month, not income arrival or transaction date', async () => {
  await write('/api/transactions', expense({ reporting_month: '2026-11' }))
  await write('/api/budgets', { name: 'Food', category_id: 2, limit_amount: 10, period: 'monthly', start_date: '2026-10-01', reporting_month: '2026-11', notify_threshold: 80 })
  expect((await guestApi('/api/budgets'))[0]).toMatchObject({ spent: 3.125, remaining: 6.875, progress: 31.25 })
  expect((await guestApi('/api/dashboard?month=2026-10')).budgets).toHaveLength(0)
  expect((await guestApi('/api/dashboard?month=2026-11')).budgets).toHaveLength(1)
})
test.each(['/api/shared/transactions', '/api/planned-transactions', '/api/notes', '/api/passkeys', '/api/backup/restore', '/api/trash'])('blocks %s without touching storage or the backend', async path => {
  readGuest(); const before = localStorage.getItem(GUEST_KEY)
  await expect(guestApi(path)).rejects.toMatchObject({ status: 403 })
  expect(localStorage.getItem(GUEST_KEY)).toBe(before)
})
test('rejects recurring, mismatched categories, missing income month and bad transfers', async () => {
  for (const row of [expense({ recurring_frequency: 'monthly' }), expense({ category_id: 10 }), expense({ type: 'income', category_id: 10 }), expense({ type: 'transfer', category_id: null, transfer_wallet_id: 1 })]) await expect(write('/api/transactions', row)).rejects.toThrow()
  expect(readGuest().transactions).toHaveLength(0)
})
test('failed storage writes and corrupt storage preserve the prior records', async () => {
  readGuest(); const before = localStorage.getItem(GUEST_KEY)
  const original = Storage.prototype.setItem
  vi.spyOn(Storage.prototype, 'setItem').mockImplementation(function(key, value) { if (key === GUEST_KEY) throw new Error('Quota'); return original.call(this, key, value) })
  await expect(write('/api/transactions', expense())).rejects.toMatchObject({ status: 507 })
  expect(localStorage.getItem(GUEST_KEY)).toBe(before)
  vi.restoreAllMocks(); localStorage.setItem(GUEST_KEY, 'corrupt')
  expect(() => readGuest()).toThrow(/not been deleted/)
  expect(localStorage.getItem(GUEST_KEY)).toBe('corrupt')
})
test('CSV is heading-based, escaped, and protected against spreadsheet formulas', async () => {
  await write('/api/transactions', expense({ description: '=DANGEROUS("a")', notes: 'Two\nlines' }))
  const csv = guestCsv()
  expect(csv).toContain('"Date","For Month","Description","Wallet"')
  expect(csv).toContain('"\'=DANGEROUS(""a"")"')
  expect(csv).toContain('"Two\nlines"')
})
test('pending imports freeze writes and clearing is revision-safe', async () => {
  const snapshot = guestImportSnapshot()
  await write('/api/transactions', expense())
  expect(clearGuest({ id: snapshot.workspace_id, revision: snapshot.revision })).toBe(false)
  localStorage.setItem(GUEST_IMPORT_KEY, JSON.stringify({ snapshot }))
  await expect(write('/api/transactions', expense())).rejects.toMatchObject({ status: 409 })
  expect(readGuest().transactions).toHaveLength(1)
})
test('account sign-out does not clear guest records or a guest draft', () => {
  readGuest()
  sessionStorage.setItem('flowbudget_tx_draft_guest', '{"description":"Guest draft"}')
  auth.clear()
  expect(sessionStorage.getItem('flowbudget_tx_draft_guest')).not.toBeNull()
  expect(localStorage.getItem(GUEST_KEY)).not.toBeNull()
})
test('guest can sign in with an existing passkey but cannot enroll one', async () => {
  setGuestActive(true)
  const fetch = vi.spyOn(globalThis, 'fetch').mockResolvedValue({ ok: true, status: 200, json: async () => ({ challenge_id: 'challenge' }) })
  expect(await api('/api/passkeys/login/options', { method: 'POST' })).toEqual({ challenge_id: 'challenge' })
  await expect(api('/api/passkeys/register/options', { method: 'POST' })).rejects.toMatchObject({ status: 403 })
  expect(fetch).toHaveBeenCalledTimes(1)
})
