export function tutorialSteps(isAdmin) {
  const steps = [
    { route: '/', selector: '.overview-balance, .hero-strip', title: 'Your overview', description: 'See your available money in personal wallets. Shared balances stay in Shared Transactions. Change the month to review income, expenses and budget progress for that period.' },
    { route: '/wallets', selector: '.section-row .button.primary', title: 'Start with a wallet', description: 'Use Add wallet for cash, a bank account or a card. Enter its starting balance once. Transactions then update that balance. Each wallet also has Edit and Delete actions.' },
    { route: '/transactions', selector: '[data-tour="add-transaction"]', title: 'Record a transaction', description: 'This opens a new transaction. Choose Expense, Income or Transfer, enter the amount and description, then pick the wallet and category. The round + in Android does the same job.' },
    { route: '/transactions', selector: '.ledger-filter-bar', title: 'Find the right records', description: 'Use the filter icon to choose wallets, month, type, search text and sort order, then Apply filters. The month arrows move between months. Remove a filter to show more records.' },
    { route: '/transactions', selector: '.transaction-wallets', title: 'Balances and corrections', description: 'Wallet balances update after saving. Select a transaction to edit, duplicate or delete it. In its form, tap the date for a calendar or the time for a clock. More options contains notes and Repeat; repeating entries need a stop date.' },
    { route: '/shared-transactions', selector: '[aria-label="Share a wallet"]', title: 'Share a wallet', description: 'Use Share a wallet to invite someone by email. Choose the wallet and their access. Use the wallet filter to separate different shared wallets, and expand Members to review who has access.' },
    { route: '/shared-transactions', selector: '[data-tour="add-transaction"]', title: 'Add shared activity', description: 'Choose the shared wallet before saving. Only wallets you can edit are available. Shared transactions affect that wallet, so check its name and amount before saving.' },
    { route: '/budgets', selector: '.section-intro .button.primary', title: 'Set a spending limit', description: 'Create a budget for one category or all expenses. Choose a limit and period. Matching expenses update its progress automatically; the pencil changes a budget and the bin deletes it.' },
    { route: '/goals', selector: '.section-intro .button-row', title: 'Plan savings and repayments', description: 'New goal sets a savings target. Add debt tracks money owed. Record contributions or repayments from the relevant card, and use its pencil when details change.' },
    { route: '/calendar', selector: '.calendar-layout', title: 'Review a day', description: 'Choose a date to see its transactions. Change the month to check earlier activity and recurring entries.' },
    { route: '/analytics', selector: '.insight-banner', title: 'Spot spending patterns', description: 'Compare income with expenses and see which categories take the largest share. Use these trends when adjusting your budgets.' },
    { route: '/notes', selector: '[aria-label="New note"]', title: 'Keep useful notes', description: 'Create a note for a shopping list, a budget plan or something to remember. Open a note to edit it, choose a paper style if needed, and save your changes.' },
    { route: '/bank-messages', selector: '.section-row', title: 'Review bank messages', description: 'Add a transaction message or follow the downloadable phone setup guide. Check each suggested amount and wallet before choosing Record expense. This is not a direct bank connection.' },
    { route: '/settings', section: 'Personal preferences', title: 'Make Budgetly comfortable', description: 'Expand Personal preferences for light or dark mode, fonts and accent colour. Apply confirms a colour choice; Save preferences saves your settings.' },
    { route: '/settings', section: 'Notifications', title: 'Keep reminders useful', description: 'Notifications are configured per browser or Android device. Choose the interval, first reminder time, quiet hours and reminder topics, then save. Browser reminders need Budgetly to stay open; Android delivery can be delayed by device battery settings.' },
    { route: '/settings', section: 'Categories', title: 'Organize categories', description: 'Expand Categories to add or edit your own income and expense categories. Use a consistent category when recording expenses so budgets and charts stay useful.' },
    { route: '/settings', section: 'Biometric sign-in', title: 'Protect your account', description: 'Biometric sign-in can register a passkey on supported devices. Your password remains a fallback. Account security contains session controls. Review confirmation prompts carefully before deleting or resetting data.' },
    { route: '/settings', section: 'Backup & restore', title: 'Protect your records', description: 'Export a JSON backup regularly and keep it somewhere private. Restoring replaces this workspace after identity confirmation, so export the current state first and use a recent backup.' },
    { route: '/settings', section: 'Reset workspace', title: 'Understand reset and recovery', description: 'Reset clears selected budget activity and saves a recovery copy. Trash and recovery copies have retention limits, so use reset and permanent deletion only when you are sure.' },
    { route: '/ask-ai', selector: '.ai-composer', title: 'Ask Budgetly', description: 'Ask about an app feature or your selected activity. Choose personal, shared or general context before sending. Built-in guidance is always available.' },
  ]
  if (isAdmin) steps.push(
    { route: '/admin', section: 'Service health', title: 'Check service health', description: 'Service health shows database, email, recovery and slow-request signals. Run a recovery snapshot and investigate repeated errors before shipping a release.' },
    { route: '/admin', section: 'Ask Budgetly', title: 'Administrator controls', description: 'The Ask Budgetly section controls whether the configured provider can be used. Review the provider, usage limits and billing before enabling it for all users.' },
    { route: '/admin', section: 'User management', title: 'Manage user access', description: 'Review accounts, disable compromised access, reset passwords carefully and keep administrator access limited to trusted operators.' },
  )
  steps.push({ route: '/', selector: '[data-tour="tutorial"]', title: 'You are ready', description: 'Start with a wallet and your first transaction. This Tutorial button is always available on Overview whenever you want another walkthrough.' })
  return steps
}
