import React, {useEffect, useRef, useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Home, UserRound, Plane, ChevronDown, ChevronRight, X, Plus, ArrowUpRight, ArrowDownLeft, LayoutDashboard, ReceiptText, Wallet, ChartNoAxesColumnIncreasing, Settings2, Moon, Sun, Check, ArrowRight, ShieldCheck, Split, CheckCircle2, Clock3, Mail} from 'lucide-react'
import './spaces.css'

const initial = [
  {id:'home',name:'Household',icon:Home,color:'#78d8bc',label:'Shared space',members:['Omar','Sara','Ali'],balance:482.75,income:850,spent:367.25,reserved:190,budgets:[['Groceries',126,180],['Transport',42,70],['Home & bills',199.25,240]],rows:[{name:'Weekly groceries',category:'Groceries',by:'Sara',amount:24.5,split:true},{name:'Internet bill',category:'Home & bills',by:'Omar',amount:12,split:true},{name:'Household contribution',category:'Income',by:'Ali',amount:150,income:true}],wallets:[['Household account',412.75],['Cash',70]],owes:18.5},
  {id:'personal',name:'Personal',icon:UserRound,color:'#aab7fa',label:'Only you',members:['Omar'],balance:245.618,income:450,spent:204.382,reserved:85,budgets:[['Groceries',38,80],['Transport',26,50],['Everyday spending',92,120]],rows:[{name:'Lunch',category:'Dining',by:'You',amount:3.25},{name:'Salary',category:'Income',by:'You',amount:450,income:true},{name:'Fuel',category:'Transport',by:'You',amount:8}],wallets:[['Main account',205.618],['Cash',40]],owes:0},
  {id:'trip',name:'Dubai trip',icon:Plane,color:'#f4b1bb',label:'Shared space',members:['Omar','Sara'],balance:320,income:600,spent:280,reserved:120,budgets:[['Stay',180,300],['Food',64,120],['Activities',36,100]],rows:[{name:'Hotel deposit',category:'Stay',by:'Omar',amount:180,split:true},{name:'Dinner reservation',category:'Food',by:'Sara',amount:24,split:true},{name:'Trip contribution',category:'Income',by:'Sara',amount:300,income:true}],wallets:[['Trip fund',320]],owes:78}
]
const nav = [['Overview',LayoutDashboard],['Transactions',ReceiptText],['Wallets',Wallet],['Budgets',ChartNoAxesColumnIncreasing]]
const money = n => `KWD ${Number(n).toFixed(3)}`
const equalShares = (amount, count) => {
  const units = Math.round(amount * 1000), base = Math.floor(units / count)
  return Array.from({length: count}, (_, i) => (base + (i < units % count ? 1 : 0)) / 1000)
}
function App(){
  const [spaces,setSpaces]=useState(initial),[active,setActive]=useState('home'),[page,setPage]=useState('Overview'),[panel,setPanel]=useState(null),[dark,setDark]=useState(true),[manageTab,setManageTab]=useState('Members'),[toast,setToast]=useState(''),[splitMode,setSplitMode]=useState('Equal'),[approvals,setApprovals]=useState({}),[invites,setInvites]=useState({})
  const space=spaces.find(s=>s.id===active), Icon=space.icon
  const modalRef = useRef(null)
  useEffect(() => {
    if (!panel) return
    const previous = document.activeElement, previousOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    modalRef.current?.querySelector('button, input, select')?.focus()
    const handleKey = event => {
      if (event.key === 'Escape') setPanel(null)
      if (event.key !== 'Tab') return
      const controls = [...modalRef.current.querySelectorAll('button:not(:disabled), input:not(:disabled), select, summary')].filter(el => el.getClientRects().length)
      const first = controls[0], last = controls.at(-1)
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus() }
      if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus() }
    }
    document.addEventListener('keydown', handleKey)
    return () => { document.body.style.overflow = previousOverflow; document.removeEventListener('keydown', handleKey); previous?.focus() }
  }, [panel])
  const notify=message=>{setToast(message);window.setTimeout(()=>setToast(''),3500)}
  const change=patch=>setSpaces(items=>items.map(s=>s.id===active?{...s,...patch}:s))
  function record(event){event.preventDefault();const data=new FormData(event.currentTarget),amount=Number(data.get('amount')); if(!Number.isFinite(amount)||amount<=0)return
    change({balance:space.balance-amount,spent:space.spent+amount,wallets:space.wallets.map(([name,balance],i)=>[name,i===0?balance-amount:balance]),rows:[{name:data.get('description'),category:'Everyday spending',by:'Omar',amount,split:space.members.length>1&&data.get('split')!=='Only me'},...space.rows]});setPanel(null);notify('Expense recorded in '+space.name)
  }
  return <div className={`preview ${dark?'dark':'light'}`}>
    <aside className="sidebar"><div className="brand"><img src="/flowbudget-logo.png" alt="Budgetly"/><div><strong>Budgetly</strong><span>Personal & shared finances</span></div></div><button className="space-switch" onClick={()=>setPanel('spaces')}><span className="space-icon" style={{color:space.color}}><Icon size={21}/></span><span><strong>{space.name}</strong><small>{space.label}</small></span><ChevronDown size={17}/></button><nav>{nav.map(([label,I])=><button key={label} className={page===label?'selected':''} onClick={()=>setPage(label)}><I size={20}/>{label}</button>)}</nav><div className="sidebar-bottom"><button className="quiet" onClick={()=>{setManageTab('Members');setPanel('manage')}}><Settings2 size={19}/>Manage space</button><div className="profile"><span className="avatar">OS</span><div>Omar Solanki<small>Space owner</small></div></div></div></aside>
    <div className="workspace"><header className="topbar"><div className="mobile-brand"><img src="/flowbudget-logo.png" alt="Budgetly"/><strong>Budgetly</strong></div><button className="mobile-switch" onClick={()=>setPanel('spaces')}><Icon size={18}/>{space.name}<ChevronDown size={15}/></button><div className="context"><span style={{color:space.color}}><Icon size={17}/>{space.name}</span><span className="divider"/>{space.label}</div><div className="header-actions"><button className="icon-button" aria-label={dark?'Light theme':'Dark theme'} title={dark?'Light theme':'Dark theme'} onClick={()=>setDark(!dark)}>{dark?<Sun size={20}/>:<Moon size={20}/>}</button><button className="icon-button" aria-label="Manage space" title="Manage space" onClick={()=>setPanel('manage')}><Settings2 size={20}/></button></div></header>
    <main key={active+page}><div className="page-title"><div><span className="eyebrow">{space.label} · October 2026</span><h1>{page}</h1></div><button className="primary desktop-add" onClick={()=>setPanel('record')}><Plus size={18}/>Add expense</button></div>
    {page==='Overview'&&<><section className="balance-band"><div><span className="muted">Available balance</span><h2>{money(space.balance)}</h2><div className="balance-meta"><ShieldCheck size={15}/>{space.id==='personal'?'Private to you':`Across ${space.wallets.length} wallet${space.wallets.length>1?'s':''} in this space`}</div></div><div className="members"><div className="avatar-stack">{space.members.map((name,i)=><span key={name} style={{background:['#364a46','#4c4050','#404660'][i%3]}}>{name[0]}</span>)}</div><button className="text-button" onClick={()=>{setManageTab('Members');setPanel('manage')}}>{space.members.length===1?'Only you':`${space.members.length} members`}<ChevronRight size={15}/></button></div></section><section className="metrics"><div><span><ArrowDownLeft size={17}/>Money in</span><strong className="positive">{money(space.income)}</strong></div><div><span><ArrowUpRight size={17}/>Spent</span><strong>{money(space.spent)}</strong></div><div><span><Clock3 size={17}/>Reserved</span><strong>{money(space.reserved)}</strong></div></section><div className="overview-grid"><section><div className="section-heading"><h3>Budget progress</h3><button className="text-button" onClick={()=>setPage('Budgets')}>View all<ArrowRight size={16}/></button></div>{space.budgets.map(([label,used,limit])=><div className="budget-row" key={label}><div><strong>{label}</strong><span>{money(used)} <small>/ {limit.toFixed(3)}</small></span></div><progress value={used} max={limit}/><small>{money(limit-used)} left</small></div>)}</section><section className="coming-up"><div className="section-heading"><h3>{space.id==='personal'?'Next payment':'Shared balance'}</h3><span className="subtle-icon">{space.id==='personal'?<Clock3 size={19}/>:<Split size={19}/>}</span></div>{space.id==='personal'?<><p className="small-label">October 12</p><h4>Phone bill</h4><strong className="medium-amount">KWD 8.000</strong><p className="muted">Reserved from your main account.</p></>:<><p className="small-label">After shared expenses</p><h4>{space.id==='trip'?'Sara owes you':'You owe Sara'}</h4><strong className="medium-amount">{money(space.owes)}</strong><button className="secondary full" onClick={()=>setPanel('settle')}>Review settlement<ArrowRight size={17}/></button><small className="muted">Balances here never include your Personal space.</small></>}</section></div><section className="activity"><div className="section-heading"><h3>Recent activity</h3><button className="text-button" onClick={()=>setPage('Transactions')}>View all<ArrowRight size={16}/></button></div><Rows space={space} onSelect={row=>{setSplitMode('Equal');setPanel({row})}}/></section></>}
    {page==='Transactions'&&<section className="transaction-page"><div className="section-heading"><h3>October activity</h3><span className="muted">{space.rows.length} records</span></div><Rows space={space} onSelect={row=>{setSplitMode('Equal');setPanel({row})}}/></section>}
    {page==='Wallets'&&<section className="wallet-grid">{space.wallets.map(([name,balance],i)=><article className={`wallet-card wallet-${i}`} key={name}><div><Wallet size={24}/><span>{space.id==='personal'?'PERSONAL':'SHARED'}</span></div><span>Available balance</span><strong>{money(balance)}</strong><h3>{name}</h3><small>{space.name}</small></article>)}</section>}
    {page==='Budgets'&&<section>{space.budgets.map(([label,used,limit])=><div className="budget-row" key={label}><div><strong>{label}</strong><span>{money(used)} / {limit.toFixed(3)}</span></div><progress value={used} max={limit}/><small>{money(limit-used)} left in October</small></div>)}</section>}
    <footer className="workspace-footer">Budgetly Spaces <span>Design preview · Sample records</span></footer></main></div>
    <nav className="bottom-nav">{nav.map(([label,I])=><button key={label} className={page===label?'selected':''} onClick={()=>setPage(label)}><I size={21}/><span>{label}</span></button>)}</nav><button className="floating-add" title="Add expense" aria-label="Add expense" onClick={()=>setPanel('record')}><Plus size={27}/></button>
    {panel&&<div className="overlay" onClick={()=>setPanel(null)}><section ref={modalRef} className={`sheet ${panel==='spaces'?'space-sheet':''}`} role="dialog" aria-modal="true" aria-label={typeof panel==='object'?'Expense details':panel==='spaces'?'Switch space':panel==='manage'?'Manage space':panel==='create'?'Create space':panel==='invite'?'Invite member':panel==='settle'?'Settlement':'Add expense'} onClick={e=>e.stopPropagation()}><div className="sheet-heading"><h2>{typeof panel==='object'?panel.row.name:({spaces:'Your spaces',manage:'Manage space',create:'Create a space',invite:'Invite a member',settle:'Settle up',record:'Add expense'})[panel]}</h2><button className="icon-button" aria-label="Close" onClick={()=>setPanel(null)}><X size={21}/></button></div>
    {panel==='spaces'&&<><div className="space-list">{spaces.map(s=>{const I=s.icon;return <button key={s.id} onClick={()=>{setActive(s.id);setPanel(null)}}><span className="space-icon" style={{color:s.color}}><I size={23}/></span><span><strong>{s.name}</strong><small>{s.id==='personal'?'Private · Only you':`${s.label} · ${s.members.length} member${s.members.length===1?'':'s'}`}</small></span>{s.id===active?<Check size={21} className="positive"/>:<ChevronRight size={18}/>}</button>})}</div><button className="secondary full" onClick={()=>setPanel('create')}><Plus size={18}/>Create space</button></>}
    {panel==='create'&&<form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget),id='space-'+Date.now();setSpaces([...spaces,{...initial[0],id,name:data.get('name'),label:'Shared space',members:['Omar'],balance:0,income:0,spent:0,reserved:0,rows:[],wallets:[['Main',0]],budgets:[],owes:0}]);setActive(id);setPage('Overview');setPanel(null);notify('Space created in this preview')}}><label>Space name<input name="name" placeholder="e.g. Family or Summer trip" required maxLength={40}/></label><label>Currency<select><option>KWD - Kuwaiti Dinar</option></select></label><p className="muted">Start on your own. Invite people when you are ready.</p><button className="primary full">Create space</button></form>}
    {panel==='manage'&&<><div className="manage-identity"><span className="space-icon" style={{color:space.color}}><Icon size={23}/></span><div><strong>{space.name}</strong><small>{space.label} · KWD</small></div></div><div className="tabs">{['Members','Controls','History'].map(tab=><button key={tab} className={manageTab===tab?'selected':''} onClick={()=>setManageTab(tab)}>{tab}</button>)}</div>{manageTab==='Members'&&<><div className="member-list">{space.members.map((name,i)=><div key={name}><span className="avatar">{name[0]}</span><span><strong>{name}{name==='Omar'?' (you)':''}</strong><small>{i===0?'Owner':i===1?'Manager':'Contributor'}</small></span>{i===0?<ShieldCheck size={18}/>:<span className="muted">Member</span>}</div>)}{(invites[active]||[]).map(email=><div key={email}><Mail size={20}/><span><strong>{email}</strong><small>Invitation pending</small></span></div>)}</div>{space.id!=='personal'&&<button className="secondary full" onClick={()=>setPanel('invite')}><Plus size={17}/>Invite member</button>}<p className="muted">{space.id==='personal'?'Your Personal space is never shared.':'Members only see records belonging to this space.'}</p></>}{manageTab==='Controls'&&<><div className="setting-row"><span><strong>Require entry approval</strong><small>Owner or manager approves member entries.</small></span><input type="checkbox" role="switch" aria-label="Require entry approval" checked={Boolean(approvals[active])} onChange={e=>setApprovals({...approvals,[active]:e.target.checked})}/></div><div className="setting-row"><span><strong>Default expense split</strong><small>Adjust for each expense.</small></span><select aria-label="Default expense split"><option>Equal</option><option>Custom</option></select></div><p className="muted">Role permissions belong to this space, not the whole account.</p></>}{manageTab==='History'&&<div className="history">{space.rows.map((row,i)=><div key={i}><CheckCircle2 size={18}/><span><strong>{row.by} recorded {row.name.toLowerCase()}</strong><small>Today · {['09:42','08:30','08:10'][i%3]}</small></span></div>)}</div>}</>}
    {panel==='invite'&&<form onSubmit={e=>{e.preventDefault();const email=new FormData(e.currentTarget).get('email');setInvites({...invites,[active]:[...invites[active]||[],email]});setPanel('manage');notify('Invitation preview added. No email was sent.')}}><label>Email<input type="email" name="email" required placeholder="name@example.com"/></label><label>Role<select><option>Contributor</option><option>Viewer</option><option>Manager</option></select></label><p className="muted">Contributor: add entries; no access to manage members.</p><button className="primary full">Invite member</button></form>}
    {panel==='record'&&<form onSubmit={record}><div className="record-context"><Icon size={16}/>{space.name}</div><label>Amount (KWD)<input type="number" name="amount" step="0.001" min="0.001" placeholder="0.000" required/></label><label>Description<input name="description" placeholder="What was this for?" required maxLength={80}/></label>{space.members.length>1&&<details><summary>Split & more options<ChevronDown size={16}/></summary><label>Split between<select name="split"><option>All members equally</option><option>Only me</option></select></label></details>}<button className="primary full">Record expense</button></form>}
    {typeof panel==='object'&&<><div className="detail-amount">{money(panel.row.amount)}</div><div className="detail-meta">{panel.row.category} · Paid by {panel.row.by}</div>{panel.row.split&&!panel.row.income?<form onSubmit={event=>{event.preventDefault();const shares=splitMode==='Equal'?equalShares(panel.row.amount,space.members.length):space.members.map((_,i)=>Number(new FormData(event.currentTarget).get('share-'+i)));if(Math.round(shares.reduce((sum,value)=>sum+value,0)*1000)!==Math.round(panel.row.amount*1000)){notify('Shares must add up to '+money(panel.row.amount));return}change({rows:space.rows.map(row=>row===panel.row?{...row,shares}:row)});setPanel(null);notify('Split confirmed in this preview')}}><h3 className="split-heading">Split between members</h3><div className="tabs">{['Equal','Custom'].map(mode=><button type="button" key={mode} className={splitMode===mode?'selected':''} onClick={()=>setSplitMode(mode)}>{mode}</button>)}</div>{space.members.map((name,i)=><div className="split-row" key={name}><span>{name}</span>{splitMode==='Equal'?<strong>{money(equalShares(panel.row.amount,space.members.length)[i])}</strong>:<input name={'share-'+i} aria-label={`Share for ${name}`} type="number" required min="0" step="0.001" defaultValue={(panel.row.shares||equalShares(panel.row.amount,space.members.length))[i].toFixed(3)}/>}</div>)}<button className="primary full">Confirm split</button></form>:<p className="muted">Recorded in {space.name}.</p>}</>}
    {panel==='settle'&&<><div className="settle-people"><span className="avatar">{space.id==='trip'?'S':'O'}</span><ArrowRight size={22}/><span className="avatar">{space.id==='trip'?'O':'S'}</span></div><p className="center muted">{space.id==='trip'?'Sara owes you':'You owe Sara'}</p><div className="detail-amount">{money(space.owes)}</div><p className="muted">Record a settlement after payment. Budgetly does not move money.</p><button className="primary full" disabled={space.owes===0} onClick={()=>{change({owes:0});setPanel(null);notify('Settlement marked as paid in this preview')}}><Check size={18}/>Mark as paid</button></>}
    </section></div>}{toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}</div>}
  </div>
}
function Rows({space,onSelect}){return <div className="rows">{space.rows.length===0?<p className="muted empty">No records yet.</p>:space.rows.map((row,i)=><button className="transaction-row" key={i} onClick={()=>onSelect(row)}><span className={`transaction-icon ${row.income?'income':''}`}>{row.income?<ArrowDownLeft size={19}/>:<ArrowUpRight size={19}/>}</span><span className="transaction-name"><strong>{row.name}</strong><small>{row.category} · {row.by}</small></span><span className="transaction-amount"><strong className={row.income?'positive':''}>{row.income?'+':'-'} {money(row.amount)}</strong><small>{row.split?'Split expense':'Recorded'}</small></span></button>)}</div>}
const root = createRoot(document.getElementById('root'))
root.render(<App/> )
if (import.meta.hot) import.meta.hot.dispose(() => root.unmount())
