import { useEffect, useState } from 'react'
import { AlertTriangle, Gauge, Plus, Trash2 } from 'lucide-react'
import { api, jsonBody, money } from '../lib/api'
import { useApp } from '../App'
import Modal from '../components/Modal'
import ProgressBar from '../components/ProgressBar'
import EmptyState from '../components/EmptyState'

const fresh=()=>({name:'',category_id:'',limit_amount:'',period:'monthly',start_date:new Date().toISOString().slice(0,10),notify_threshold:80})
export default function Budgets(){
  const {settings,refreshKey,refresh,notify}=useApp(); const [rows,setRows]=useState([]); const [cats,setCats]=useState([]); const [open,setOpen]=useState(false); const [form,setForm]=useState(fresh()); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  const load=()=>Promise.all([api('/api/budgets'),api('/api/categories?kind=expense')]).then(([b,c])=>{setRows(b);setCats(c)})
  useEffect(()=>{load()},[refreshKey])
  const fmt=v=>money(v,settings.currency,settings.compact_numbers)
  const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/api/budgets',{method:'POST',...jsonBody({...form,category_id:form.category_id?Number(form.category_id):null,limit_amount:Number(form.limit_amount),notify_threshold:Number(form.notify_threshold)})});setOpen(false);setForm(fresh());refresh();notify('Budget created')}catch(err){setError(err.message)}finally{setBusy(false)}}
  const remove=async id=>{if(!confirm('Delete this budget?'))return;await api(`/api/budgets/${id}`,{method:'DELETE'});refresh();notify('Budget deleted')}
  return <div className="stack gap-20">
    <section className="section-intro glass"><div><p className="eyebrow">Guardrails, not guilt</p><h2>Give your spending a comfortable edge.</h2><p className="muted">Budgets automatically measure expense transactions in the matching period.</p></div><button className="button primary" onClick={()=>setOpen(true)}><Plus/>New budget</button></section>
    <section className="cards-grid">{rows.length?rows.map(b=><article className="budget-card glass" key={b.id}><div className="card-top"><span className="round-icon"><Gauge size={19}/></span><button className="row-icon danger" onClick={()=>remove(b.id)}><Trash2 size={16}/></button></div><div><p className="eyebrow">{b.category_name||'All expenses'} · {b.period}</p><h3>{b.name}</h3></div><div className="budget-amounts"><strong>{fmt(b.spent)}</strong><span>of {fmt(b.limit_amount)}</span></div><ProgressBar value={b.progress} warning={b.progress>=b.notify_threshold}/><div className="budget-foot"><span>{Math.round(b.progress)}% used</span><strong>{fmt(b.remaining)} left</strong></div>{b.progress>=b.notify_threshold&&<div className="budget-alert"><AlertTriangle size={15}/>Reached your {b.notify_threshold}% alert point</div>}</article>):<div className="panel glass full-span"><EmptyState title="No spending limits yet" text="Create a category budget and FlowBudget will keep its pulse visible."/></div>}</section>
    <Modal open={open} onClose={()=>setOpen(false)} title="Create budget" subtitle="Pick a category or track all expenses together."><form onSubmit={submit} className="stack gap-16"><label className="field"><span>Name</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Dining this month"/></label><div className="form-grid two"><label className="field"><span>Category</span><select value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">All expenses</option>{cats.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="field"><span>Limit</span><input required type="number" min="0.001" step="0.001" value={form.limit_amount} onChange={e=>setForm({...form,limit_amount:e.target.value})}/></label><label className="field"><span>Period</span><select value={form.period} onChange={e=>setForm({...form,period:e.target.value})}><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label><label className="field"><span>Notify threshold (%)</span><input type="number" min="1" max="100" value={form.notify_threshold} onChange={e=>setForm({...form,notify_threshold:e.target.value})}/></label></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button className="button ghost" type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="button primary" disabled={busy}>Create budget</button></div></form></Modal>
  </div>
}
