import { useEffect, useState } from 'react'
import { CalendarClock, Coins, HandCoins, Plus, Target, Trash2 } from 'lucide-react'
import { api, jsonBody, money } from '../lib/api'
import { useApp } from '../App'
import Modal from '../components/Modal'
import ProgressBar from '../components/ProgressBar'
import EmptyState from '../components/EmptyState'

export default function GoalsDebts(){
  const {settings,refreshKey,refresh,notify}=useApp(); const [goals,setGoals]=useState([]); const [debts,setDebts]=useState([]); const [mode,setMode]=useState(null); const [action,setAction]=useState(null); const [form,setForm]=useState({}); const [amount,setAmount]=useState('')
  const load=()=>Promise.all([api('/api/goals'),api('/api/debts')]).then(([g,d])=>{setGoals(g);setDebts(d)})
  useEffect(()=>{load()},[refreshKey]); const fmt=v=>money(v,settings.currency,settings.compact_numbers)
  const openGoal=()=>{setForm({name:'',target_amount:'',current_amount:0,deadline:'',icon:'target',color:'#0a4173'});setMode('goal')}; const openDebt=()=>{setForm({name:'',kind:'owed',principal:'',remaining:'',interest_rate:0,due_date:'',minimum_payment:0,notes:''});setMode('debt')}
  const submit=async e=>{e.preventDefault(); if(mode==='goal')await api('/api/goals',{method:'POST',...jsonBody({...form,target_amount:Number(form.target_amount),current_amount:Number(form.current_amount||0),deadline:form.deadline||null})}); else await api('/api/debts',{method:'POST',...jsonBody({...form,principal:Number(form.principal),remaining:Number(form.remaining||form.principal),interest_rate:Number(form.interest_rate||0),minimum_payment:Number(form.minimum_payment||0),due_date:form.due_date||null})}); setMode(null);refresh();notify(mode==='goal'?'Goal created':'Debt added')}
  const contribute=async()=>{if(!amount)return;await api(action.type==='goal'?`/api/goals/${action.id}/contribute`:`/api/debts/${action.id}/pay`,{method:'POST',...jsonBody({amount:Number(amount)})});setAction(null);setAmount('');refresh();notify(action.type==='goal'?'Goal contribution recorded':'Debt payment recorded')}
  const remove=async(type,id)=>{if(!confirm(`Delete this ${type}?`))return;await api(`/api/${type==='goal'?'goals':'debts'}/${id}`,{method:'DELETE'});refresh();notify(`${type==='goal'?'Goal':'Debt'} deleted`)}
  return <div className="stack gap-22">
    <section className="section-intro glass"><div><p className="eyebrow">Forward motion</p><h2>Save toward good things. Finish what you owe.</h2><p className="muted">Goals and debts live side by side so progress stays visible.</p></div><div className="button-row"><button className="button ghost" onClick={openDebt}><HandCoins/>Add debt</button><button className="button primary" onClick={openGoal}><Plus/>New goal</button></div></section>
    <div className="split-title"><div><Target/><div><p className="eyebrow">Savings</p><h3>Goals</h3></div></div></div>
    <section className="cards-grid">{goals.length?goals.map(g=><article className="goal-card glass" key={g.id}><div className="card-top"><span className="round-icon"><Target/></span><button className="row-icon danger" onClick={()=>remove('goal',g.id)}><Trash2/></button></div><h3>{g.name}</h3><p className="muted">{g.deadline?`Target date ${new Date(g.deadline+'T12:00:00').toLocaleDateString()}`:'No deadline — move at your pace'}</p><div className="goal-number"><strong>{fmt(g.current_amount)}</strong><span>/ {fmt(g.target_amount)}</span></div><ProgressBar value={g.progress}/><div className="budget-foot"><span>{g.progress}% complete</span><button className="text-button" onClick={()=>setAction({type:'goal',id:g.id,name:g.name})}>Add money</button></div></article>):<div className="panel glass full-span"><EmptyState title="No goals yet" text="Create a target and make progress visible."/></div>}</section>
    <div className="split-title"><div><HandCoins/><div><p className="eyebrow">Obligations</p><h3>Debts</h3></div></div></div>
    <section className="cards-grid">{debts.length?debts.map(d=><article className="debt-card glass" key={d.id}><div className="card-top"><span className="round-icon"><Coins/></span><button className="row-icon danger" onClick={()=>remove('debt',d.id)}><Trash2/></button></div><div><p className="eyebrow">{d.kind==='owed'?'You owe':'Owed to you'}</p><h3>{d.name}</h3></div><div className="goal-number"><strong>{fmt(d.remaining)}</strong><span>remaining</span></div><ProgressBar value={d.progress}/><div className="debt-meta"><span><CalendarClock/> {d.due_date||'No due date'}</span><span>{d.interest_rate}% interest</span></div><div className="budget-foot"><span>{d.progress}% cleared</span>{d.kind==='owed'&&<button className="text-button" onClick={()=>setAction({type:'debt',id:d.id,name:d.name})}>Record payment</button>}</div></article>):<div className="panel glass full-span"><EmptyState title="No debts tracked" text="Add an installment, loan, or money owed to you."/></div>}</section>
    <Modal open={!!mode} onClose={()=>setMode(null)} title={mode==='goal'?'Create savings goal':'Add debt'}>{mode&&<form onSubmit={submit} className="stack gap-16"><label className="field"><span>Name</span><input required value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label>{mode==='goal'?<div className="form-grid two"><label className="field"><span>Target amount</span><input required type="number" min="0.001" step="0.001" value={form.target_amount||''} onChange={e=>setForm({...form,target_amount:e.target.value})}/></label><label className="field"><span>Already saved</span><input type="number" min="0" step="0.001" value={form.current_amount||0} onChange={e=>setForm({...form,current_amount:e.target.value})}/></label><label className="field"><span>Deadline</span><input type="date" value={form.deadline||''} onChange={e=>setForm({...form,deadline:e.target.value})}/></label></div>:<div className="form-grid two"><label className="field"><span>Type</span><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="owed">I owe this</option><option value="receivable">Owed to me</option></select></label><label className="field"><span>Original amount</span><input required type="number" min="0.001" step="0.001" value={form.principal||''} onChange={e=>setForm({...form,principal:e.target.value,remaining:form.remaining||e.target.value})}/></label><label className="field"><span>Remaining</span><input required type="number" min="0" step="0.001" value={form.remaining||''} onChange={e=>setForm({...form,remaining:e.target.value})}/></label><label className="field"><span>Interest %</span><input type="number" min="0" step="0.01" value={form.interest_rate||0} onChange={e=>setForm({...form,interest_rate:e.target.value})}/></label><label className="field"><span>Due date</span><input type="date" value={form.due_date||''} onChange={e=>setForm({...form,due_date:e.target.value})}/></label><label className="field"><span>Minimum payment</span><input type="number" min="0" step="0.001" value={form.minimum_payment||0} onChange={e=>setForm({...form,minimum_payment:e.target.value})}/></label></div>}<div className="modal-actions"><button type="button" className="button ghost" onClick={()=>setMode(null)}>Cancel</button><button className="button primary">Save</button></div></form>}</Modal>
    <Modal open={!!action} onClose={()=>setAction(null)} title={action?.type==='goal'?'Add to goal':'Record debt payment'} subtitle={action?.name}><div className="stack gap-16"><label className="amount-input"><span>Amount</span><input autoFocus type="number" min="0.001" step="0.001" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.000"/></label><div className="modal-actions"><button className="button ghost" onClick={()=>setAction(null)}>Cancel</button><button className="button primary" disabled={!amount} onClick={contribute}>Record</button></div></div></Modal>
  </div>
}
