import { useEffect, useRef, useState } from 'react'
import { Camera, Download, Fingerprint, Image, Mountain, Pencil, Plus, RefreshCcw, Save, ShieldCheck, Trash2, Upload, UserRound, X } from 'lucide-react'
import { api, jsonBody } from '../lib/api'
import { useApp } from '../App'
import Modal from '../components/Modal'
import { configureReminder, isNativeApp, testNotification } from '../lib/deviceNotifications'
import { biometricSupported, disableBiometric, setupBiometric, cancelBiometric, passwordOnlyEnabled } from '../lib/biometric'
import DeviceSignInPreference from '../components/DeviceSignInPreference'
import PasswordInput from '../components/PasswordInput'

const imageData = async (file, maxBytes, label) => {
  if (!file) throw new Error(`Choose a ${label.toLowerCase()} first`)
  if (!['image/png', 'image/jpeg', 'image/webp'].includes(file.type)) throw new Error(`${label} must be PNG, JPEG, or WebP`)
  if (file.size > maxBytes) throw new Error(`${label} is too large`)
  const bitmap = await createImageBitmap(file)
  try {
    const maxSide = label === 'Wallpaper' ? 1920 : 256
    const scale = Math.min(1, maxSide / Math.max(bitmap.width, bitmap.height))
    const canvas = document.createElement('canvas')
    canvas.width = Math.max(1, Math.round(bitmap.width * scale))
    canvas.height = Math.max(1, Math.round(bitmap.height * scale))
    canvas.getContext('2d').drawImage(bitmap, 0, 0, canvas.width, canvas.height)
    return canvas.toDataURL('image/webp', .85)
  } finally { bitmap.close() }
}

export default function Settings(){
  const {user,settings,setSettings,appearance,setAppearance,reloadSettings,refresh,notify,lock,confirm}=useApp()
  const [form,setForm]=useState(settings)
  const [cats,setCats]=useState([])
  const [catOpen,setCatOpen]=useState(false)
  const [editingCat,setEditingCat]=useState(null)
  const [clearOpen,setClearOpen]=useState(false)
  const [clearScope,setClearScope]=useState('budget')
  const [clearConfirm,setClearConfirm]=useState('')
  const [recovery,setRecovery]=useState([])
  const [cat,setCat]=useState({name:'',kind:'expense',icon:'circle',color:'#0a4173'})
  const [biometric,setBiometric]=useState(false)
  const [passkeyPassword,setPasskeyPassword]=useState('')
  const [passkeyBusy,setPasskeyBusy]=useState(false)
  const [passwordOnly,setPasswordOnly]=useState(passwordOnlyEnabled)
  useEffect(() => () => cancelBiometric(), [])
  useEffect(() => { api('/api/passkeys').then(r => setBiometric(r.enabled)).catch(e => notify(e.message, 'error')) }, [notify])
  const inputRef=useRef(null)
  const profileRef=useRef(null)
  const wallpaperRef=useRef(null)
  useEffect(()=>setForm(settings),[settings])
  useEffect(()=>{api('/api/categories').then(setCats);api('/api/recovery').then(setRecovery).catch(()=>{})},[])
  const save=async e=>{e.preventDefault();try{await configureReminder(form);const updated=await api('/api/settings',{method:'PUT',...jsonBody(form)});setSettings(updated);if(!isNativeApp()&&form.reminders_enabled&&'Notification' in window&&Notification.permission==='default'){const permission=await Notification.requestPermission();notify(permission==='granted'?'Settings saved. Browser reminders enabled':'Settings saved. In-app reminders remain enabled')}else notify('Settings saved')}catch(err){notify(err.message,'error')}}
  const deleteAccount=async()=>{if(!await confirm('Permanently delete your account and all private data? This cannot be undone.'))return;try{await api('/api/account',{method:'DELETE'});lock()}catch(err){notify(err.message,'error')}}
  const saveCat=async e=>{e.preventDefault();try{await api(editingCat?`/api/categories/${editingCat.id}`:'/api/categories',{method:editingCat?'PUT':'POST',...jsonBody(cat)});setCats(await api('/api/categories'));setCatOpen(false);setEditingCat(null);setCat({name:'',kind:'expense',icon:'circle',color:'#0a4173'});refresh();notify(editingCat?'Category updated':'Category added')}catch(err){notify(err.message,'error')}}
  const editCat=c=>{setEditingCat(c);setCat({name:c.name,kind:c.kind,icon:c.icon||'circle',color:c.color||'#0a4173'});setCatOpen(true)}
  const removeCat=async c=>{if(!await confirm(`Delete ${c.name}?`))return;try{await api(`/api/categories/${c.id}`,{method:'DELETE'});setCats(await api('/api/categories'));refresh();notify('Category deleted')}catch(err){notify(err.message,'error')}}
  const exportBackup=async()=>{const data=await api('/api/backup');const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`flowbudget-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);notify('Backup exported')}
  const restore=async e=>{const file=e.target.files?.[0]; if(!file)return; try{const data=JSON.parse(await file.text());await api('/api/backup/restore',{method:'POST',body:JSON.stringify(data)});await reloadSettings();refresh();setCats(await api('/api/categories'));notify('Backup restored')}catch(err){notify(`Restore failed: ${err.message}`,'error')} finally {e.target.value=''}}
  const clearWorkspace=async e=>{e.preventDefault();try{const result=await api('/api/workspace/clear',{method:'POST',...jsonBody({confirmation:'CLEAR',scope:clearScope})});await reloadSettings();refresh();setCats(await api('/api/categories'));setRecovery(await api('/api/recovery'));setClearOpen(false);setClearConfirm('');notify(`Workspace cleared. Recovery copy #${result.recovery_id} was saved.`)}catch(err){notify(err.message,'error')}}
  const downloadRecovery=async id=>{try{const data=await api(`/api/recovery/${id}`);const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`flowbudget-recovery-${id}.json`;a.click();URL.revokeObjectURL(url)}catch(err){notify(err.message,'error')}}

  const updateAppearance=async patch=>{const updated=await api('/api/account/appearance',{method:'PUT',...jsonBody(patch)});setAppearance(updated);return updated}
  const pickProfile=async e=>{const file=e.target.files?.[0];try{const data=await imageData(file,1_000_000,'Profile picture');await updateAppearance({profile_image:data});notify('Profile picture updated')}catch(err){notify(err.message,'error')}finally{e.target.value=''}}
  const pickWallpaper=async e=>{const file=e.target.files?.[0];try{const data=await imageData(file,2_500_000,'Wallpaper');await updateAppearance({wallpaper_image:data});notify('Wallpaper updated')}catch(err){notify(err.message,'error')}finally{e.target.value=''}}
  const clearAppearance=async key=>{try{await updateAppearance({[key]:''});notify(key==='profile_image'?'Profile picture removed':'Wallpaper removed')}catch(err){notify(err.message,'error')}}
  const enableBiometric=async()=>{if(passkeyBusy)return;setPasskeyBusy(true);try{await setupBiometric(user.email,passkeyPassword);setBiometric(true);setPasskeyPassword('');notify('Passkey registered')}catch(err){notify(err.name==='NotAllowedError'?'Passkey setup cancelled':err.message,'error')}finally{setPasskeyBusy(false)}}
  const disableDeviceSignIn=async()=>{if(passkeyBusy)return;setPasskeyBusy(true);try{await disableBiometric();setBiometric(false);notify('All passkeys revoked')}catch(err){notify(err.message,'error')}finally{setPasskeyBusy(false)}}

  return <div className="settings-grid">
    <section className="panel glass"><h3>Personal preferences</h3><form onSubmit={save} className="stack gap-16">
      <label className="field"><span>Font</span><select aria-label="Font" value={form.font_family || 'system'} onChange={e => setForm({...form, font_family:e.target.value})}><option value="system">System</option><option value="arial">Arial</option><option value="georgia">Georgia</option><option value="verdana">Verdana</option></select></label>
      <label className="field"><span>Text colour</span><select aria-label="Text colour" value={form.text_color || 'ink'} onChange={e => setForm({...form, text_color:e.target.value})}><option value="ink">Ink</option><option value="charcoal">Charcoal</option><option value="forest">Forest</option></select></label>
      <label className="field"><span>Accent colour</span><input aria-label="Accent colour" type="color" value={form.accent_color || '#0a4173'} onChange={e => setForm({...form, accent_color:e.target.value})}/></label>
      <label className="check-row"><input type="checkbox" checked={!!form.reminders_enabled} onChange={e => setForm({...form, reminders_enabled:e.target.checked})}/><span>Daily transaction reminder</span></label>
      {form.reminders_enabled && <><label className="field"><span>Reminder time (this device's time)</span><input required type="time" value={form.reminder_time || '20:00'} onChange={e => setForm({...form, reminder_time:e.target.value})}/></label><p className="muted">Installed mobile apps schedule device reminders. Browser reminders require FlowBudget to remain open.</p><button type="button" className="button ghost" onClick={async () => { if (isNativeApp()) { try { await testNotification(); notify('Test notification scheduled') } catch(e) { notify(e.message, 'error') } return } if (!('Notification' in window)) return notify('This browser does not support notifications.', 'error'); try { const permission = await Notification.requestPermission(); notify(permission === 'granted' ? 'Browser notifications enabled' : 'In-app reminders remain available') } catch { notify('Notifications are unavailable in this browser.', 'error') } }}>{isNativeApp() ? 'Test device notification' : 'Enable browser notifications'}</button></>}
      <button className="button primary"><Save/>Save preferences</button>
    </form></section>
    <section className="panel glass"><div className="panel-head"><div><p className="eyebrow">Preferences</p><h3>Display & locale</h3></div></div><form onSubmit={save} className="stack gap-16"><label className="field"><span>Budget name</span><input value={form.display_name||''} onChange={e=>setForm({...form,display_name:e.target.value})}/></label><div className="form-grid two"><label className="field"><span>Currency</span><input value={form.currency||'KWD'} maxLength="6" onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></label><label className="field"><span>Week starts on</span><select value={form.week_starts_on||'sunday'} onChange={e=>setForm({...form,week_starts_on:e.target.value})}><option value="sunday">Sunday</option><option value="monday">Monday</option></select></label></div><label className="check-row"><input type="checkbox" checked={!!form.compact_numbers} onChange={e=>setForm({...form,compact_numbers:e.target.checked})}/><span>Use compact large numbers where possible</span></label><button className="button primary self-start"><Save/>Save preferences</button></form></section>

    <section className="panel glass"><div className="panel-head"><div><p className="eyebrow">Account</p><h3>Profile & session</h3></div><ShieldCheck className="muted-icon"/></div><div className="security-card"><div className="profile-account-row">{appearance.profile_image?<img className="settings-avatar" src={appearance.profile_image} alt="Profile"/>:<span className="settings-avatar fallback"><Mountain/></span>}<div><strong>{user?.username}</strong><p className="muted">{user?.email} · {user?.role === 'admin' ? 'Administrator' : 'User'} access</p></div></div><div className="button-row"><button className="button ghost small" onClick={()=>profileRef.current?.click()}><Camera/>Change photo</button>{appearance.profile_image&&<button className="button ghost small" onClick={()=>clearAppearance('profile_image')}><X/>Remove</button>}<button className="button ghost small" onClick={lock}>Sign out</button></div><input ref={profileRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={pickProfile}/></div></section>
<section className="panel glass"><div className="panel-head"><div><p className="eyebrow">Quick access</p><h3>Biometric sign-in</h3></div><Fingerprint className="muted-icon"/></div><p className="muted">Use Face ID, Touch ID, Windows Hello, or your device passkey to unlock this device faster. Your password remains available as a fallback.</p><div className="stack gap-12"><DeviceSignInPreference disabled={passkeyBusy} onChange={setPasswordOnly}/>{!passwordOnly && <label className="field"><span>Confirm password to register a passkey</span><PasswordInput autoComplete="current-password" value={passkeyPassword} onChange={e=>setPasskeyPassword(e.target.value)}/></label>}{biometric && <button className="button ghost" disabled={passkeyBusy} onClick={disableDeviceSignIn}>Revoke all passkeys</button>}{<button className="button primary" disabled={!biometricSupported() || passkeyBusy || passkeyPassword.length < 8} onClick={enableBiometric}><Fingerprint/>{passkeyBusy ? 'Registering...' : biometric ? 'Register another passkey' : 'Enable biometric sign-in'}</button>}</div>{!biometricSupported()&&<small className="muted">{passwordOnly ? 'Password-only sign-in is enabled for this device.' : 'Passkeys require a supported browser and HTTPS.'}</small>}</section>
    <section className="panel glass danger-zone"><div className="panel-head"><div><p className="eyebrow">Danger zone</p><h3>Delete account</h3></div></div><p className="muted">Permanently removes your account, wallets, transactions, notes, feedback, and settings.</p><button className="button danger" onClick={deleteAccount}><Trash2/>Delete my account</button></section>

    <section className="panel glass span-2-settings appearance-panel"><div className="panel-head"><div><p className="eyebrow">Personalization</p><h3>Workspace wallpaper</h3></div><Image className="muted-icon"/></div><div className="wallpaper-settings"><div className={`wallpaper-preview ${appearance.wallpaper_image?'has-image':''}`} style={appearance.wallpaper_image?{backgroundImage:`url(${JSON.stringify(appearance.wallpaper_image)})`}:{}}>{!appearance.wallpaper_image&&<><Image/><span>No wallpaper selected</span></>}</div><div className="stack gap-10"><p className="muted">Your wallpaper is private to your account. FlowBudget’s glass panels stay translucent above it.</p><div className="button-row"><button className="button primary small" onClick={()=>wallpaperRef.current?.click()}><Upload/>Choose wallpaper</button>{appearance.wallpaper_image&&<button className="button ghost small" onClick={()=>clearAppearance('wallpaper_image')}><Trash2/>Remove wallpaper</button>}</div><small className="appearance-hint">PNG, JPEG, or WebP · maximum 2.5 MB</small></div><input ref={wallpaperRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={pickWallpaper}/></div></section>

    <section className="panel glass span-2-settings"><div className="panel-head"><div><p className="eyebrow">Organization</p><h3>Categories</h3></div><button className="button ghost small" onClick={()=>{setEditingCat(null);setCat({name:'',kind:'expense',icon:'circle',color:'#0a4173'});setCatOpen(true)}}><Plus/>Add category</button></div><div className="category-settings">{cats.map(c=><div key={c.id}><span><i style={{background:c.color}}/>{c.name}<small>{c.kind}</small></span><div className="button-row"><button className="row-icon" aria-label={`Edit ${c.name}`} onClick={()=>editCat(c)}><Pencil/></button><button className="row-icon danger" onClick={()=>removeCat(c)}><Trash2/></button></div></div>)}</div></section>

    <section className="panel glass"><div className="panel-head"><div><p className="eyebrow">Portability</p><h3>Backup & restore</h3></div></div><p className="muted">Export a JSON snapshot of your workspace. Other users and passwords are never included.</p><div className="stack gap-10"><button className="button ghost full" onClick={exportBackup}><Download/>Export backup</button><button className="button ghost full" onClick={()=>inputRef.current?.click()}><Upload/>Restore backup</button><input ref={inputRef} hidden type="file" accept="application/json,.json" onChange={restore}/></div></section>

    <section className="panel glass"><div className="panel-head"><div><p className="eyebrow">Fresh start</p><h3>Reset workspace</h3></div><RefreshCcw className="muted-icon"/></div><p className="muted">Clear budget activity and extra wallets. Your default Main Wallet stays available at zero, and categories are preserved.</p><button className="button ghost full" onClick={()=>setClearOpen(true)}><RefreshCcw/>Reset workspace</button>{recovery.length>0&&<div className="recovery-list"><small className="muted">Recent recovery copies</small>{recovery.slice(0,3).map(item=><button key={item.id} className="recovery-row" onClick={()=>downloadRecovery(item.id)}><span><strong>{item.reason}</strong><small>{new Date(item.created_at).toLocaleString()}</small></span><Download size={15}/></button>)}</div>}</section>

    <Modal open={catOpen} onClose={()=>setCatOpen(false)} title={editingCat?'Edit category':'Add category'}><form onSubmit={saveCat} className="stack gap-16"><label className="field"><span>Name</span><input required value={cat.name} onChange={e=>setCat({...cat,name:e.target.value})}/></label><div className="form-grid two"><label className="field"><span>Type</span><select value={cat.kind} onChange={e=>setCat({...cat,kind:e.target.value})}><option value="expense">Expense</option><option value="income">Income</option></select></label><label className="field"><span>Accent</span><input type="color" value={cat.color} onChange={e=>setCat({...cat,color:e.target.value})}/></label></div><div className="modal-actions"><button type="button" className="button ghost" onClick={()=>setCatOpen(false)}>Cancel</button><button className="button primary">{editingCat?'Save category':'Add category'}</button></div></form></Modal>
    <Modal open={clearOpen} onClose={()=>setClearOpen(false)} title="Reset workspace"><form onSubmit={clearWorkspace} className="stack gap-16"><p className="muted">This only affects your account. Type <strong>CLEAR</strong> to confirm. Categories are never removed by this action. Recovery copy will be available in Settings.</p><label className="field"><span>What should be cleared?</span><select value={clearScope} onChange={e=>setClearScope(e.target.value)}><option value="budget">Budget data and extra wallets</option><option value="workspace">Budget data, extra wallets, and Notes</option></select></label><label className="field"><span>Confirmation</span><input required value={clearConfirm} onChange={e=>setClearConfirm(e.target.value)} placeholder="Type CLEAR" autoComplete="off"/></label><div className="modal-actions"><button type="button" className="button ghost" onClick={()=>setClearOpen(false)}>Cancel</button><button className="button danger" disabled={clearConfirm !== 'CLEAR'}>Reset workspace</button></div></form></Modal>
  </div>
}
