import { useEffect, useState } from 'react'
import { LogOut, KeyRound, RefreshCw, Trash2 } from 'lucide-react'
import { api } from '../lib/api'
import { showTime } from '../lib/time'
import { useApp } from '../App'

export default function AccountSecurity(){
  const {notify,confirm,lock}=useApp()
  const [sessions,setSessions]=useState([]),[keys,setKeys]=useState([]),[events,setEvents]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const load=async()=>{try{const[s,k,a]=await Promise.all([api('/api/account/sessions'),api('/api/passkeys/list'),api('/api/account/activity')]);setSessions(s);setKeys(k);setEvents(a);setError('')}catch(e){setError(e.message)}}
  useEffect(()=>{load()},[])
  const act=async(operation)=>{if(busy)return;setBusy(true);try{await operation();await load()}catch(e){notify(e.message,'error')}finally{setBusy(false)}}
  return <section className="panel glass span-2-settings"><div className="panel-head"><h3>Account security</h3><button className="icon-button" title="Refresh security activity" aria-label="Refresh security activity" onClick={load}><RefreshCw size={18}/></button></div>{error&&<p role="alert" className="form-error">{error}</p>}<details className="ledger-disclosure"><summary>Signed-in sessions ({sessions.length})</summary><div className="security-items">{sessions.map(s=><div className="security-item" key={s.id}><div><strong>{s.current?'This session':'Other session'}</strong><small>{s.label}</small><small>Last active {showTime(s.last_seen)} Kuwait</small></div><button className="icon-button" disabled={busy} title="Sign out session" aria-label="Sign out session" onClick={()=>act(async()=>{await api(`/api/account/sessions/${s.id}`,{method:'DELETE'});if(s.current)lock()})}><LogOut size={18}/></button></div>)}</div><button className="button ghost" disabled={busy} onClick={()=>act(async()=>{if(!await confirm('Sign out all devices, including this one?'))return;await api('/api/account/signout-all',{method:'POST'});lock()})}><LogOut size={16}/>Sign out everywhere</button></details><h4>Registered passkeys</h4>{keys.length===0?<p className="muted">No passkeys registered.</p>:keys.map((k,i)=><div className="security-item" key={k.id}><span><KeyRound size={16}/> Passkey {i+1} · {k.fingerprint}</span><button className="icon-button" disabled={busy} title="Revoke this passkey" aria-label="Revoke this passkey" onClick={()=>act(async()=>{if(await confirm('Revoke this passkey? Other passkeys remain available.'))await api(`/api/passkeys/item/${encodeURIComponent(k.id)}`,{method:'DELETE'})})}><Trash2 size={18}/></button></div>)}<details><summary>Recent account activity</summary><div className="security-items">{events.map(e=><div className="security-item" key={e.id}><div><strong>{e.action}</strong><small>{e.actor} · {e.resource} · {showTime(e.created_at)} Kuwait</small></div></div>)}</div></details></section>
}
