import {useState} from 'react'
import {BellRing} from 'lucide-react'
import {testNotification,isNativeApp} from '../lib/deviceNotifications'
import {useApp} from '../App'

export default function NotificationPreferences({form,setForm}){
  const {notify}=useApp()
  const [busy,setBusy]=useState(false)
  const [permission,setPermission]=useState(()=>isNativeApp()?'Check with test notification':('Notification' in window?Notification.permission:'unsupported'))
  return <div className="stack gap-12"><p className="muted">Time zone: Kuwait (UTC+03:00). Notification permission: {permission}. {isNativeApp()?'Mobile reminders are scheduled for the next 30 days and refreshed when you open the app.':'Browser reminders require FlowBudget to be open. Closed-browser delivery is unavailable.'}</p><button type="button" className="button ghost" disabled={busy} onClick={async()=>{setBusy(true);try{await testNotification();notify('Test notification sent');setPermission('granted')}catch(e){notify(e.message,'error');if('Notification' in window)setPermission(Notification.permission)}finally{setBusy(false)}}}><BellRing size={16}/>{busy?'Sending...':'Send test notification'}</button><label className="check-row"><input type="checkbox" checked={!!form.quiet_hours_enabled} onChange={e=>setForm({...form,quiet_hours_enabled:e.target.checked})}/>Quiet hours</label>{form.quiet_hours_enabled&&<div className="form-grid two"><label className="field"><span>Quiet hours start (Kuwait)</span><input type="time" value={form.quiet_start||'22:00'} onChange={e=>setForm({...form,quiet_start:e.target.value})}/></label><label className="field"><span>Quiet hours end (Kuwait)</span><input type="time" value={form.quiet_end||'08:00'} onChange={e=>setForm({...form,quiet_end:e.target.value})}/></label></div>}<fieldset><legend>Daily reminder topics</legend>{[['daily','Transaction entry'],['budgets','Budget limits'],['bills','Recurring bills'],['debts','Debt payments']].map(([key,label])=><label className="check-row" key={key}><input type="checkbox" checked={(form.reminder_topics||['daily']).includes(key)} onChange={e=>setForm({...form,reminder_topics:e.target.checked?[...(form.reminder_topics||['daily']),key]:(form.reminder_topics||['daily']).filter(x=>x!==key)})}/>{label}</label>)}</fieldset></div>
}
