import { useState } from 'react'
import { Upload, Download } from 'lucide-react'
import Modal from './Modal'
import { api,jsonBody,money } from '../lib/api'
import { useApp } from '../App'

export default function StatementImport({wallets, compact = false}){
  const {settings,refresh,notify}=useApp()
  const [open,setOpen]=useState(false),[wallet,setWallet]=useState(''),[text,setText]=useState(''),[rows,setRows]=useState([]),[selected,setSelected]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const preview=async event=>{event.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await api('/api/statements/preview',{method:'POST',...jsonBody({text,wallet_id:Number(wallet)})});setRows(r);setSelected(r.filter(x=>!x.error&&!x.duplicate).map(x=>x.line))}catch(e){setError(e.message)}finally{setBusy(false)}}
  const save=async()=>{if(busy)return;setBusy(true);try{const result=await api('/api/statements/import',{method:'POST',...jsonBody({transactions:rows.filter(r=>selected.includes(r.line)).map(r=>r.transaction)})});notify(`${result.imported} imported; ${result.skipped} duplicates skipped`);setOpen(false);setText('');setRows([]);refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <><button className={compact ? "icon-button" : "button ghost"} title="Import statement" aria-label="Import statement" onClick={()=>setOpen(true)}><Upload size={18}/>{!compact && "Import statement"}</button><Modal open={open} onClose={()=>!busy&&setOpen(false)} title="Import statement" size="large"><form className="stack gap-16" onSubmit={preview}><p className="muted">CSV columns: date, description, amount, type (income or expense). Use YYYY-MM-DD or YYYY-MM-DDTHH:mm in Kuwait time. Up to 500 rows.</p><a href="/statement-example.csv" download className="button ghost"><Download size={16}/>Download example CSV</a><label className="field"><span>Wallet</span><select required value={wallet} onChange={e=>{setWallet(e.target.value);setRows([])}}><option value="">Choose wallet</option>{wallets.filter(w=>!w.archived).map(w=><option value={w.id} key={w.id}>{w.name} · {money(w.balance,settings.currency)}</option>)}</select></label><label className="field"><span>CSV statement</span><input required type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files[0];setRows([]);if(!file)return;if(file.size>1000000){setError('Choose a CSV smaller than 1 MB');return}setText(await file.text());setError('')}}/></label><button className="button ghost" disabled={busy||!text||!wallet}>{busy?'Processing...':'Preview rows'}</button></form>{error&&<p className="form-error" role="alert">{error}</p>}{rows.length>0&&<><div className="import-preview">{rows.map(r=><label className="security-item" key={r.line}><input type="checkbox" disabled={busy||!!r.error||r.duplicate} checked={selected.includes(r.line)} onChange={e=>setSelected(s=>e.target.checked?[...s,r.line]:s.filter(x=>x!==r.line))}/><span>Row {r.line}: {r.error||`${r.transaction.description} · ${r.transaction.amount} · ${r.transaction.date.slice(0,16)}`}{r.duplicate?' · Already recorded':''}</span></label>)}</div><button className="button primary" disabled={busy||!selected.length} onClick={save}>{busy?'Importing...':`Import ${selected.length} rows`}</button></>}</Modal></>
}
